CXX = g++
CXXFLAGS = -I C:\Users\zacha\Documents\eigen-3.4.0\ -I C:\CImg-3.3.3 -Wall -o3

seamCarve:
	$(CXX) $(CXXFLAGS) seamCarve.cpp -o seamCarve

matrixTest:
	$(CXX) -I C:\Users\zacha\Documents\eigen-3.4.0\ matrixTest.cpp -o matrixTest

clean:
	rm *.o
	rm *~